server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;

    location / { index PaginaInicial.html; }
    location /recetas  { index Recetas.html; }
    location /registro { index Registro.html; }
    location /ia-chef  { index IaChef.html; }
    location /calendario { index Calendario.html; }
    location /admin    { index Admin.html; }
}
