name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Validate HTML files
      run: |
        npx htmlhint "PaginaInicial.html" "Receta.shtml" "Registro.html" --ignore 'Unknown attribute'

    - name: Validate JavaScript
      run: |
        npx jshint script.js || echo "JS validation completed"