name: JavaScript CI

on:
    push:
        branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --save-dev jest jest-environment-jsdom

      - name: Run tests
        run: npm test

      - name: Validate HTML syntax
      run: |
        echo "🔍 Validando sintaxis HTML..."
        npx htmlhint "Pagina inicial.html" "Receta.shtml" "Registro.html" --ignore 'Unknown attribute' || echo "HTML validation completed with warnings"

    # VALIDACIÓN DE JAVASCRIPT
    - name: Validate JavaScript syntax
      run: |
        echo "🔍 Validando sintaxis JavaScript..."
        npx jshint JS/script.js --verbose || echo "JavaScript validation completed with warnings"

    # VALIDACIÓN DE CSS (si tienes archivos CSS)
    - name: Validate CSS syntax
      run: |
        echo "🔍 Validando sintaxis CSS..."
        if [ -d "css" ]; then
          find css -name "*.css" -exec npx csslint {} \; || echo "CSS validation completed with warnings"
        else
          echo "No se encontró directorio CSS, omitiendo validación"
        fi

    # EJECUCIÓN DE TESTS
    - name: Run tests with Jest
      run: |
        echo "🧪 Ejecutando tests..."
        npx jest --ci --verbose --passWithNoTests

    # VERIFICACIÓN DE ESTRUCTURA DE ARCHIVOS
    - name: Verify project structure
      run: |
        echo "📁 Verificando estructura del proyecto..."
        if [ ! -f "Pagina inicial.html" ]; then echo "⚠️  Advertencia: Pagina inicial.html no encontrado"; fi
        if [ ! -f "Receta.shtml" ]; then echo "⚠️  Advertencia: Receta.shtml no encontrado"; fi
        if [ ! -f "Registro.html" ]; then echo "⚠️  Advertencia: Registro.html no encontrado"; fi
        if [ ! -f "JS/script.js" ]; then echo "⚠️  Advertencia: JS/script.js no encontrado"; fi
        if [ ! -d "tests" ]; then echo "⚠️  Advertencia: Directorio tests no encontrado"; fi

        echo "✅ Verificación de estructura completada"
