# .github/workflows/javascript.yml
name: JavaScript CI
on:
  push:
    branches: [ main ]
jobs:
 test:
 runs-on: ubuntu-latest
 steps:
 - uses: actions/checkout@v3
 - name: Setup Node.js
 uses: actions/setup-node@v3
 with:
 node-version: '18'
 - name: Install dependencies
 run: npm install --save-dev jest jest-environment-jsdom
 - name: Run tests
 run: npm test
 - name: Validate HTML structure
   uses: htmlhint/htmlhint-action@v1
   with:
     files: src/index.html
